services:
  server:
    build:
      context: .
      tags:
        - "kiss-requirements:latest"
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      HOST: "0.0.0.0"
      WORKERS: "1"