on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: Docker Image CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Image CI
    strategy:
      matrix:
        sub-project:
          - "."
          - "step-1-kiss-requirements"
          - "step-2-kiss-poetry"
          - "step-3-basic-improvements"
          - "step-4-nontrivial-improvements"
          - "step-5-larger-project"
          - "extra-1-compiling-dependencies"
          - "extra-2-need-for-speed"
          - "extra-3-moving-complexity"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5.1.0
        with:
          push: false
          context: ${{ matrix.sub-project }}
